#Assignment 4
#Tasks
Perform the Below Tasks to complete the assignment:-
* Download the Dataset:- [Dataset](https://storage.googleapis.com/kagglesdsdata/datasets/483/982/spam.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20221027%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20221027T040626Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=763d74492f8b1288d9a1653ea4751167b85c6fc632171111e2b3f89804cbb53d5b1b4ca293a93882909db46217a0bdcfc7f703bd4f1d23e6948877de4e222b492fc59357afe1bb53cf44be9e3cb0ab7b4be23409435e8bf4648720b62562d9ba8c1e7460fb0d30f4c248f94c40fdcaf9ff197aaf12b83b9a9079881fdf04c3f0bb2bce3c305cb1fec2b9eb962695b59b24e27dd41385e92cfcbbe3923d44821301a628f4df6e538c02a60f5352d1c5198c1836fc07269f0d1c3c214afe1c4e865ff86ae58a66e65b81e202bc1a6d9dbb71ef6c867db6b20423cdbc6d5400f6eebcb558df0e3bc6f4294425f803f2d528fcb8e2273a069229fe4a827f325b1944)
* Import required library
* Read dataset and do pre-processing
* Create Model
* Add Layers (LSTM, Dense-(Hidden Layers), Output)
* Compile the Model
* Fit the Model
* Save The Model
* Test The Model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#1. Load the dataset

In [ ]:
dataset_location = "/content/drive/MyDrive/IBM/spam.csv"

#2. Import the library

In [ ]:
import pandas as pd
import nltk
import re
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.translate.ribes_score import word_rank_alignment
from numpy.lib.shape_base import split
from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import LSTM,Dense,Dropout,Input,Embedding,Activation,Flatten
from keras.models import Model
import nltk 

#3. Read dataset and do preprocessing

In [ ]:
data = pd.read_csv(dataset_location,encoding = "ISO-8859-1")

In [ ]:
data.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis = 1,inplace = True)
data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
nltk.download('stopwords',quiet=True)
nltk.download('all',quiet=True)

True

In [ ]:
ps = PorterStemmer()
input = []

In [ ]:
for i in range(0,5572):
  v2 = data['v2'][i]

  #removing punctuation
  v2 = re.sub('[^a-zA-Z]',' ',v2)

  #converting to lower case
  v2 = v2.lower()

  #splitting the sentence
  v2 = v2.split()

  #removing the stopwords and stemming
  v2 = [ps.stem(word) for word in v2 if not word in set(stopwords.words('english'))]

  v2 = ' '.join(v2)

  input.append(v2)

In [ ]:
#creating document term matrix
cv = CountVectorizer(max_features=2000)
x = cv.fit_transform(input).toarray()
x.shape

(5572, 2000)

In [ ]:

le = preprocessing.LabelEncoder()

data['v1'] = le.fit_transform(data['v1'])
data['v1'].unique()

array([0, 1])

In [ ]:
y = data['v1'].values

In [ ]:
y = y.reshape(-1,1)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.4)

#4. Model building - Adding layers, Compiling model and saving model

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(1565,activation = "relu"))
model.add(Dense(3000,activation = "relu"))
model.add(Dense(1,activation = "sigmoid"))
model.add(Flatten())

In [ ]:
model.compile(optimizer = "adam",loss = "binary_crossentropy", metrics = ["accuracy"])

In [ ]:
model.fit(x_train,y_train,epochs = 15)

In [ ]:
model.save("spam-message-classifier.h5")

#5. Testing the model

In [ ]:
ham = "im donee. come pick me up"
spam = "WINNER$$$$ SMS REPLY 'WIN'"
message = re.sub('[^a-zA-Z]',' ',spam)
message

'WINNER     SMS REPLY  WIN '

# Testing with spam message

In [ ]:
message = message.split()
message = [ps.stem(word) for word in message if not word in set(stopwords.words('english')) ]
message = ' '.join(message)

In [ ]:
message1 = cv.transform([message])
message1

<1x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [ ]:
TruePredction = model.predict(message1.astype(float))

1/1 [==============================] - 0s 13ms/step


In [ ]:
TruePredction > 0.5

array([[ True]])

# Testing with normal message 


In [ ]:
msg = re.sub('[^a-zA-Z]',' ',ham)
msg

'im donee  come pick me up'

In [ ]:
msg = msg.split()
msg = [ps.stem(word) for word in msg if not word in set(stopwords.words('english'))]
msg = ' '.join(msg)

In [ ]:
msg

'im done come pick'

In [ ]:
cv.transform([msg])

<1x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [ ]:
FalsePredection = model.predict(cv.transform([msg]))

1/1 [==============================] - 0s 110ms/step


In [ ]:
FalsePredection > 0.5

array([[False]])